version: '2'

services:
  db:
    image: mysql:5.6
    container_name: sync2_mysql
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: Admin123
    ports:
      - "${MYSQL_DEV_PORT}:3306"
    volumes:
      - ./dbdump:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  child1:
    build:
      context: instance
      args:
        INSTANCE_NAME: child1
    image: referenceapplication_child1:2.6.1
    container_name: sync2_child1
    depends_on:
      - db
    environment:
      DB_DATABASE: child1
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
      DEBUG: 'true'
    ports:
      - "${TOMCAT_DEV_PORT_CHILD1}:8080"
      - "${TOMCAT_DEV_DEBUG_PORT_CHILD1}:1044"
    volumes:
      - child1-data:/usr/local/tomcat/.OpenMRS
      - ./modules:/usr/local/tomcat/.OpenMRS/modules/
      - child2-data:/root/projectDir

  child2:
    build:
      context: instance
      args:
        INSTANCE_NAME: child2
    image: referenceapplication_child2:2.6.1
    container_name: sync2_child2
    depends_on:
      - db
    environment:
      DB_DATABASE: child2
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
      DEBUG: 'true'
    ports:
      - "${TOMCAT_DEV_PORT_CHILD2}:8080"
      - "${TOMCAT_DEV_DEBUG_PORT_CHILD2}:1044"
    volumes:
      - child2-data:/usr/local/tomcat/.OpenMRS
      - ./modules:/usr/local/tomcat/.OpenMRS/modules/
      - child2-data:/root/projectDir

  parent:
    build:
      context: instance
      args:
        INSTANCE_NAME: parent
    image: referenceapplication_parent:2.6.1
    container_name: sync2_parent
    depends_on:
      - db
    environment:
      DB_DATABASE: parent
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: Admin123
      DB_CREATE_TABLES: 'false'  # change to 'true' if using an empty database
      DB_AUTO_UPDATE: 'false'    # change to 'true' if using an empty database
      MODULE_WEB_ADMIN: 'true'   # allow web admin on OpenMRS
      DEBUG: 'true'
    ports:
      - "${TOMCAT_DEV_PORT_PARENT}:8080"
      - "${TOMCAT_DEV_DEBUG_PORT_PARENT}:1044"
    volumes:
      - parent-data:/usr/local/tomcat/.OpenMRS
      - ./modules:/usr/local/tomcat/.OpenMRS/modules/
      - parent-data:/root/projectDir

volumes:
  db-data:
  child1-data:
  child2-data:
  parent-data:
